"""Delete book field

Revision ID: 4c6a8bff75ec
Revises: 65c3ad4310e9
Create Date: 2025-01-27 16:47:17.746018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6a8bff75ec'
down_revision: Union[str, None] = '65c3ad4310e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
